### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by MrBlasyMSK** [Hydros01/WorldBorder#2]
These part dont work
```yml
send-border-title: true
border-title: "Turn around"
```
```yml
#Will the player fling away from the world edge?
fling: true
```
```yml
#Force teleports the player to server spawn (This happens if they pearl past the WorldBorder - they will freeze)
force-spawn: true
```
Sorry my last issue sucks

**Comment by MrBlasyMSK** [comment]
I mean they don't work in game, you can try it yourself.

**Comment by Hydros01** [comment]
Hi, I have found out why this is happening and I will correct it within the next few hours. (As I am currently busy).

Thanks for reporting this, your feedback is helpful 😄
